name: Continuous integration

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate-docker-build:
    name: Validate if docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build & tag docker image
        uses: AplinkosMinisterija/reusable-workflows/.github/actions/docker-build-tag-push@main
        with:
          environment: test
          push: false
