name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Build
        run: yarn run build
        env:
          VITE_NODE_ENV: development
          VITE_GA_ENV: development
          VITE_MAPS_HOST: https://dev-maps.biip.lt

      - uses: actions/upload-artifact@v4
        with:
          name: page
          path: dist

  publish-preview:
    name: Publish preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    timeout-minutes: 10
    needs: build-test
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Publish preview to Cloudflare pages
        uses: AplinkosMinisterija/reusable-workflows/.github/actions/cloudflare-pages-publish@main
        with:
          cloudflare-api-token: ${{ secrets.BIIP_CLOUDFLARE_PAGES_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.BIIP_CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: smalsuolis-wed
          artifact-name: page

  validate-docker-build:
    name: Validate if docker image builds
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & tag docker image
        uses: AplinkosMinisterija/reusable-workflows/.github/actions/docker-build-tag-push@main
        with:
          environment: test
          push: false
