name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  deploy-staging:
    name: Deploy staging
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: staging
      docker-image: ghcr.io/AplinkosMinisterija/smalsuolis-web
      enable-sentry: true
      runs-on: ubuntu-latest
      build-args: |
        VITE_NODE_ENV=production
        VITE_GA_ENV=staging
        VITE_SENTRY_ENV=staging
        VITE_SENTRY_DSN=https://868f3858116e484e838dc4f966bbd5f8@sentry.biip.lt/48
        VITE_MAPS_HOST=https://staging-maps.biip.lt
